---
samza_jobs_dir: /home/hduser/samza-jobs/{{env}}
job_status_file: /home/hduser/samza-jobs/{{env}}/extract/job_status
yarn_path: /usr/local/hadoop/bin
object_denormalization_additional_config_dir: /etc/samza-jobs/{{env}}
object_denormalization_additional_config: "{{object_denormalization_additional_config_dir}}/object-denormalization-additional-config.json"
es_router_additional_config: "{{object_denormalization_additional_config_dir}}/es-router-additional-config.json"
es_router_additional_secondary_config: "{{object_denormalization_additional_config_dir}}/es-router-additional-secondary-config.json"
lpdeploy: no
dpdeploy: no
hadoop_version: 2.7.2
# Defaults
telemetry_extractor_yarn_container_count: 1
telemetry_validator_yarn_container_count: 1
telemetry_de_duplication_yarn_container_count: 1
telemetry_router_yarn_container_count: 1
telemetry_reverse_search_yarn_container_count: 1
telemetry_object_de_normalization_yarn_container_count: 1
telemetry_es_indexer_yarn_container_count: 1
telemetry_location_updater_yarn_container_count: 1

max_iteration_count_for_samza_job: 2
